namespace IdentityServer.Shared.Enums;

public enum FailureTypes
{
    APPLICATION_EXCEPTION,
    DATABASE_EXCEPTION,
    VALIDATION_EXCEPTION,
    MAIL_EXCEPTION,

    INVALID_REQUEST,

    USER_NOT_FOUND,
    TAKEN_USERNAME,
    REGISTERED_USER,
    CURRENT_PASSWORD_DID_NOT_MATCH,
    VERIFY_EMAIL_FAILED,
    UPDATE_USER_FAILED,
    CREATE_USER_FAILED,
    CREATE_EXTERNAL_LOGIN_FAILED,
    ADD_ROLE_TO_USER_FAILED,
    CHANGE_PASSWORD_FAILED,
    CHANGE_EMAIL_FAILED,
    RESET_PASSWORD_FAILED,
    CONFIRM_EMAIL_FAILED,
    UPDATE_SECURITY_STAMP_FAILED,

    INVALID_TFA_CODE,
    TFA_ALREADY_ENABLED,
    RESET_TFA_KEY_FAILED,
    ENABLE_TFA_KEY_FAILED,

    INVALID_CODE,
    UNVERIFIED_CODE,
}
